[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure static assets are properly handled
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure API routes are handled correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Handle client-side routing for SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Handle Next.js client-side routing
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Ensure all other routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200
  force = false